SET VERIFY OFF
SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE grade(n NUMBER) IS
BEGIN
	IF n>90 THEN 
		DBMS_OUTPUT.PUT_LINE('0');
	ELSIF n>80 THEN
		DBMS_OUTPUT.PUT_LINE('E');
	ELSIF n>70 THEN
		DBMS_OUTPUT.PUT_LINE('A');
	ELSIF n>60 THEN
		DBMS_OUTPUT.PUT_LINE('B');
	ELSIF n>50 THEN
		DBMS_OUTPUT.PUT_LINE('C');
	ELSIF n>40 THEN
		DBMS_OUTPUT.PUT_LINE('D');
	ELSE
		DBMS_OUTPUT.PUT_LINE('Fail');
	END IF;
END;
/
SHOW ERRORS;
ACCEPT n NUMBER PROMPT 'Enter the marks: '
BEGIN
	grade(&n);
END;
/
