SET VERIFY OFF
SET SERVEROUTPUT ON
CREATE TABLE SPHERE(rad NUMBER(2),area NUMBER(10,2),volume NUMBER(20,2));

BEGIN
 for r in 1..20 LOOP
 	INSERT INTO SPHERE VALUES(
 	r,
 	4*3.14*r*r,
 	(4.0/3.0)*3.14*r*r*r
 	);
 END LOOP;
 COMMIT;
END;
/
SELECT * FROM SPHERE;
